# Generated by Django 3.0.2 on 2020-01-25 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('old_price', models.FloatField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('gender', models.BooleanField()),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('postal_code', models.CharField(max_length=16)),
                ('house_number_additions', models.CharField(max_length=16)),
                ('street_name', models.CharField(max_length=64)),
                ('city_name', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=16)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
