# Generated by Django 3.0.2 on 2020-01-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://cdn.webshopapp.com/shops/270696/files/290927874/800x1024x2/loveramics-loveramics-starsky-250-ml-mug.jpg', max_length=64),
            preserve_default=False,
        ),
    ]
